default_stages: [pre-commit]
exclude: |
  ^migrations/.*|       # Exclude files in any 'migrations' folder
  ^venv/.*|             # Exclude the virtual environment directory
  ^static/.*|           # Exclude static files
  .*\.pyc$|             # Exclude Python bytecode files
  .*__pycache__/.*      # Exclude __pycache__ directories

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--line-length", "108"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--max-line-length", "108"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
